base_url = "/oat-glassed/"
title = "Oat Glassed UI"
compile_sass = false
build_search_index = false

[markdown]
highlighting = { theme = "one-dark-pro" }

[extra]
description = "Oat Glassed - Ultra-lightweight, semantic, zero-dependency HTML UI component library"
